### ISSUE TITLE
set_and_get.py実行時に発生するエラー（HTTPSリクエストがタイムアウト）について

### ISSUE THREAD

**Issue by hayasheesh** [takuroumi/der_tester#16]
# 概要
環境設定を完了し、set_and_get.pyを実行したのですが、エラーが返ってきました。
１週間ほど前までは正常に利用できたのですが、ここ１週間はずっとエラーが発生しています。
# 再現手順
１環境構築を完了する
２set_and_get.pyを実行する
# エラー内容
```
/usr/bin/env` /usr/local/bin/python /home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 42391 -- /workspaces/der_tester/tools/scripts/iothub/set_and_get.py 
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='trial-hub.iot-exchange.net', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/der_tester/tools/scripts/iothub/set_and_get.py", line 75, in <module>
    response_get1 = requests.request("POST", url, headers=headers, json=payload_get, timeout=20)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='trial-hub.iot-exchange.net', port=443): Read timed out. (read timeout=20)

```
# 見解
このエラーは、HTTPSリクエストがタイムアウトしたことを示しています。具体的には、requests.request関数を呼び出した際に、HTTPSリクエストの読み取り操作がタイムアウト(20秒)になったことが原因です。
urllib3ライブラリ内のHTTPSConnectionPoolがHTTPSリクエストを処理している際に、サーバーからのレスポンスを読み取る操作でタイムアウトが発生しました。
タイムアウトが発生する主な原因は以下が考えられます。

１ネットワーク接続が不安定で、サーバーとの通信に時間がかかりすぎた
２サーバー側でレスポンスの処理に時間がかかりすぎた
３タイムアウト値(20秒)が適切でなかった

と思われますが、どのように対応すべきでしょうか？アドバイスを頂きますと嬉しいです。

**Comment by iot-ex** [comment]
設置させていただいているIoTルータ(ミニPC)の電源が入っているかをご確認ください。

**Comment by takuroumi** [comment]
こちら、現在もご状況は継続しておりますでしょうか…？

**Comment by hayasheesh** [comment]
> こちら、現在もご状況は継続しておりますでしょうか…？

報告遅れてしまい申し訳ありません。先日iot-exさんに相談させて頂き、IoTルータの交換などにより解消しました。
@iot-ex さん、  @takuroumi さん、ありがとうございました。
引き続きよろしくお願いいたします。

**Comment by Honekawasujiemon** [comment]
良かったです。東大馬場
